// The page: Now, Look up and Month views. Everything is worked out in the
// browser from rota.json and the people data built into js/data.js.

import { monthView, otherParent, responsibleAt, type Parent, type Responsibility } from '../rota/engine.ts';
import { loadRota, validatePeople, type People, type Person } from '../rota/load.ts';
import { addDays, londonDate, londonTime, londonToInstant, TIME_ZONE } from '../rota/time.ts';
// @ts-expect-error: generated by the build
import { rota, people as rawPeople } from './data.js';

const cfg = loadRota(rota);
const people: People = validatePeople(rawPeople);
const children = new Intl.ListFormat('en-GB', { type: 'conjunction' }).format(people.children);

// ---------------------------------------------------------------------------
// Small DOM helper. Text is always set with textContent, never as HTML.

type Child = Node | string | null | undefined | false;

function el(tag: string, attrs: Record<string, string> = {}, ...kids: Child[]): HTMLElement {
  const node = document.createElement(tag);
  for (const [k, v] of Object.entries(attrs)) node.setAttribute(k, v);
  for (const k of kids) if (k) node.append(k);
  return node;
}

function byId(id: string): HTMLElement {
  return document.getElementById(id)!;
}

// ---------------------------------------------------------------------------
// Formatting

const dayFmt = new Intl.DateTimeFormat('en-GB', { timeZone: TIME_ZONE, weekday: 'short', day: 'numeric', month: 'short' });
const longFmt = new Intl.DateTimeFormat('en-GB', { timeZone: TIME_ZONE, weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' });
const monthFmt = new Intl.DateTimeFormat('en-GB', { timeZone: 'UTC', month: 'long', year: 'numeric' });

/** "today 17:00", "tomorrow 08:45" or "Mon 15 Jun 08:45", relative to `ref`. */
function when(instant: number, ref: number): string {
  const d = londonDate(instant);
  const t = londonTime(instant);
  if (d === londonDate(ref)) return `today ${t}`;
  if (d === addDays(londonDate(ref), 1)) return `tomorrow ${t}`;
  return `${dayFmt.format(instant)} ${t}`;
}

function telHref(phone: string): string {
  return 'tel:' + phone.replace(/[^\d+]/g, '');
}

function initials(name: string): string {
  return name.split(/\s+/).filter(Boolean).map((w) => w[0].toUpperCase()).join('').slice(0, 3);
}

function nameOf(p: Parent | null): string {
  return p ? people.parents[p].name : 'nobody set';
}

// ---------------------------------------------------------------------------
// The contact card used by Now and Look up

function card(r: Responsibility, isNow: boolean): HTMLElement {
  if (!r.parent) {
    return el('div', { class: 'card' },
      el('p', { class: 'kicker' }, 'No rota is set for this time. Please contact either parent:'),
      ...(['A', 'B'] as Parent[]).map((p) => backup(p, 'Contact')));
  }
  const p = people.parents[r.parent];
  const kicker = isNow
    ? `Right now ${children} are with`
    : `On ${longFmt.format(r.at)} at ${londonTime(r.at)}, ${children} are with`;
  return el('div', { class: `card p${r.parent}` },
    el('p', { class: 'kicker' }, kicker),
    el('p', { class: 'who' }, p.name),
    callOrNote(p),
    p.email && el('a', { class: 'email', href: `mailto:${p.email}` }, p.email),
    el('p', { class: 'until' },
      'Until ', el('strong', {}, when(r.until, r.at)), ', then ', el('strong', {}, nameOf(r.next)), '.'),
    r.segment.source === 'override' &&
      el('p', { class: 'note' }, 'Change to the usual rota' + (overrideNote(r) ? `: ${overrideNote(r)}` : '')),
    backup(otherParent(r.parent), 'If no answer, contact'));
}

function overrideNote(r: Responsibility): string {
  return cfg.overrides.find((o) => o.id === r.segment.overrideId)?.note ?? '';
}

function backup(p: Parent, label: string): HTMLElement {
  const x = people.parents[p];
  return el('div', { class: 'backup' },
    el('p', { class: 'kicker' }, label),
    el('p', { class: 'name' }, x.name),
    callOrNote(x));
}

function callOrNote(x: Person): HTMLElement {
  return x.phone
    ? el('a', { class: 'call', href: telHref(x.phone) }, `Call ${x.phone}`)
    : el('p', { class: 'no-phone' }, 'Use the number on school records');
}

// ---------------------------------------------------------------------------
// Views

function renderNow(): void {
  const now = Date.now();
  byId('view-now').replaceChildren(card(responsibleAt(now, cfg, 'viewer'), true),
    el('p', { class: 'kicker' }, `Updated ${londonTime(now)} UK time.`));
}

function renderLookup(): void {
  const d = (byId('lookup-date') as HTMLInputElement).value;
  const t = (byId('lookup-time') as HTMLInputElement).value;
  const out = byId('lookup-result');
  if (!d || !t) return void out.replaceChildren();
  out.replaceChildren(card(responsibleAt(londonToInstant(d, t), cfg, 'viewer'), false));
}

let shownYear = 0;
let shownMonth = 0;

function renderMonth(): void {
  const days = monthView(shownYear, shownMonth, cfg, 'viewer');
  byId('month-title').textContent = monthFmt.format(Date.UTC(shownYear, shownMonth - 1, 1));

  byId('month-legend').replaceChildren(
    ...(['A', 'B'] as Parent[]).map((p) =>
      el('span', {}, el('span', { class: `swatch p${p}` }), [people.parents[p].name, people.parents[p].phone].filter(Boolean).join(' '))),
    el('span', {}, '\u21c4 handover time'),
    el('span', {}, '* change to usual rota'),
  );

  const today = londonDate(Date.now());
  const head = el('tr', {}, ...['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((d) => el('th', {}, d)));
  const rows: HTMLElement[] = [];
  const firstWeekday = (new Date(Date.UTC(shownYear, shownMonth - 1, 1)).getUTCDay() + 6) % 7;
  let row = el('tr');
  for (let i = 0; i < firstWeekday; i++) row.append(el('td', { class: 'nb' }));
  for (const day of days) {
    if (row.children.length === 7) {
      rows.push(row);
      row = el('tr');
    }
    const cls = [day.nightParent ? `p${day.nightParent}` : '', day.date === today ? 'today' : ''].join(' ').trim();
    row.append(el('td', { class: cls },
      el('span', { class: 'd' }, String(Number(day.date.slice(8))) + (day.hasOverride ? ' *' : '')),
      day.nightParent && el('div', { class: 'p' },
        el('span', { class: 'full' }, people.parents[day.nightParent].name),
        el('span', { class: 'short' }, initials(people.parents[day.nightParent].name))),
      ...day.handovers.map((h) => el('span', { class: 'h', title: `${h.time} to ${nameOf(h.to)}` }, `\u21c4 ${h.time}`))));
  }
  while (row.children.length < 7) row.append(el('td', { class: 'nb' }));
  rows.push(row);
  byId('month-grid').replaceChildren(el('thead', {}, head), el('tbody', {}, ...rows));
  byId('month-footer').textContent =
    `Colour shows who has ${children} overnight. \u21c4 shows the time they change over (UK time). Printed ${longFmt.format(Date.now())}.`;
}

// ---------------------------------------------------------------------------
// Navigation

const views = ['now', 'lookup', 'month'] as const;

function show(): void {
  const current = views.find((v) => location.hash === `#${v}`) ?? 'now';
  for (const v of views) byId(`view-${v}`).hidden = v !== current;
  for (const a of document.querySelectorAll('nav a')) {
    if ((a as HTMLElement).dataset.view === current) a.setAttribute('aria-current', 'page');
    else a.removeAttribute('aria-current');
  }
  if (current === 'now') renderNow();
  if (current === 'lookup') renderLookup();
  if (current === 'month') renderMonth();
}

function start(): void {
  byId('title').textContent = `Who to contact for ${children}`;
  byId('school').textContent = people.school;
  document.title = `Who to contact: ${children}`;

  const now = Date.now();
  (byId('lookup-date') as HTMLInputElement).value = londonDate(now);
  (byId('lookup-time') as HTMLInputElement).value = londonTime(now);
  byId('lookup-form').addEventListener('input', renderLookup);
  byId('lookup-form').addEventListener('submit', (e) => e.preventDefault());

  const [y, m] = londonDate(now).split('-').map(Number);
  shownYear = y;
  shownMonth = m;
  const step = (delta: number) => {
    shownMonth += delta;
    if (shownMonth < 1) { shownMonth = 12; shownYear--; }
    if (shownMonth > 12) { shownMonth = 1; shownYear++; }
    renderMonth();
  };
  byId('month-prev').addEventListener('click', () => step(-1));
  byId('month-next').addEventListener('click', () => step(1));
  byId('month-print').addEventListener('click', () => window.print());

  window.addEventListener('hashchange', show);
  document.addEventListener('visibilitychange', () => document.visibilityState === 'visible' && show());
  setInterval(() => !byId('view-now').hidden && renderNow(), 30_000);
  show();
}

start();
