// Shows the name of the parent who has the children right now, plus a date
// box to check who has them on any other day.

import { dayTimeline, responsibleAt, type Parent } from '../rota/engine.ts';
import { loadRota } from '../rota/load.ts';
import { londonDate } from '../rota/time.ts';
// @ts-expect-error: generated by the build
import { rota } from './data.js';

const cfg = loadRota(rota);
const dayFmt = new Intl.DateTimeFormat('en-GB', { timeZone: 'UTC', weekday: 'short', day: 'numeric', month: 'short' });

function nameOf(p: Parent | null): string {
  return p ? rota.names[p] : 'nobody set';
}

function renderNow(): void {
  const parent = responsibleAt(Date.now(), cfg, 'viewer').parent;
  const name = parent ? rota.names[parent] : '';
  document.getElementById('who')!.textContent = name;
  document.title = name || 'Rota';
}

/** e.g. "Fri 9 Oct: Anna until 08:45, then Doug" or "Sat 10 Oct: Doug all day". */
function describe(date: string): string {
  const day = dayTimeline(date, cfg, 'viewer');
  const [y, m, d] = date.split('-').map(Number);
  const label = dayFmt.format(Date.UTC(y, m - 1, d)).replace(',', '');
  if (day.changes.length === 0) return `${label}: ${nameOf(day.startParent)} all day`;
  let text = `${label}: ${nameOf(day.startParent)} until ${day.changes[0].time}`;
  day.changes.forEach((c, i) => {
    const next = day.changes[i + 1];
    text += `, then ${nameOf(c.to)}` + (next ? ` until ${next.time}` : '');
  });
  return text;
}

const input = document.getElementById('date') as HTMLInputElement;
function renderDate(): void {
  document.getElementById('answer')!.textContent = input.value ? describe(input.value) : '';
}

input.value = londonDate(Date.now());
// Phones differ in which event they send when the calendar closes, so listen
// for both, and give a button for anyone who expects to press one.
input.addEventListener('input', renderDate);
input.addEventListener('change', renderDate);
document.getElementById('show')!.addEventListener('click', renderDate);
renderDate();

renderNow();
setInterval(renderNow, 30_000);
document.addEventListener('visibilitychange', () => document.visibilityState === 'visible' && renderNow());
