// Shows the name of the parent who has the children right now, and nothing else.

import { responsibleAt } from '../rota/engine.ts';
import { loadRota } from '../rota/load.ts';
// @ts-expect-error: generated by the build
import { rota } from './data.js';

const cfg = loadRota(rota);

function render(): void {
  const parent = responsibleAt(Date.now(), cfg, 'viewer').parent;
  const name = parent ? rota.names[parent] : '';
  document.getElementById('who')!.textContent = name;
  document.title = name || 'Rota';
}

render();
setInterval(render, 30_000);
document.addEventListener('visibilitychange', () => document.visibilityState === 'visible' && render());
